module Constants
 COMMIT_MESSAGE    = 'AutoUpdate Production Rollout Log'
 DEPLOY_REPO_NAME  = ENV['DEPLOY_REPO_NAME']
 HTML_FILENAME     = ENV['HTML_FILENAME']
 MARKDOWN_FILENAME = ENV['MARKDOWN_FILENAME']
 PAGES_BRANCH      = ENV['PAGES_BRANCH']
 PAGES_REPO_NAME   = ENV['PAGES_REPO_NAME']
end
